# plot history
import matplotlib.pyplot as plt
import pickle
import os

# --- CONFIGURATION ---
# These must match the filenames generated by your 4_server.py
FEDAVG_HIST = "results/fedavg_history.pkl"
FEDPROX_HIST = "results/fedprox_history.pkl"

def load_data(filepath):
    """
    Loads the history file and extracts (Round, Loss, Accuracy, F1).
    """
    if not os.path.exists(filepath):
        print(f"⚠️ Warning: {filepath} not found.")
        return [], [], [], []
    
    with open(filepath, "rb") as f:
        history = pickle.load(f)
        
    rounds = []
    losses = []
    accuracies = []
    f1s = []
    
    for entry in history:
        rounds.append(entry.get('round'))
        losses.append(entry.get('train_loss'))
        accuracies.append(entry.get('accuracy'))
        f1s.append(entry.get('f1'))
            
    return rounds, losses, accuracies, f1s

def plot_comparison():
    print("Loading history files...")
    
    # Load Data
    r_avg, l_avg, a_avg, f_avg = load_data(FEDAVG_HIST)
    r_prox, l_prox, a_prox, f_prox = load_data(FEDPROX_HIST)
    
    if not r_avg and not r_prox:
        print("❌ No data found.")
        return

    # Create Subplots (Loss, Accuracy, F1)
    fig, axs = plt.subplots(1, 3, figsize=(18, 5))
    
    # 1. Loss Plot
    if r_avg: axs[0].plot(r_avg, l_avg, label='FedAvg', color='blue', marker='o')
    if r_prox: axs[0].plot(r_prox, l_prox, label='FedProx', color='red', linestyle='--', marker='x')
    axs[0].set_title('Training Loss')
    axs[0].set_xlabel('Round')
    axs[0].set_ylabel('Loss')
    axs[0].legend()
    axs[0].grid(True)
    
    # 2. Accuracy Plot
    if r_avg: axs[1].plot(r_avg, a_avg, label='FedAvg', color='blue', marker='o')
    if r_prox: axs[1].plot(r_prox, a_prox, label='FedProx', color='red', linestyle='--', marker='x')
    axs[1].set_title('Global Accuracy')
    axs[1].set_xlabel('Round')
    axs[1].set_ylabel('Accuracy')
    axs[1].legend()
    axs[1].grid(True)

    # 3. F1 Plot
    if r_avg: axs[2].plot(r_avg, f_avg, label='FedAvg', color='blue', marker='o')
    if r_prox: axs[2].plot(r_prox, f_prox, label='FedProx', color='red', linestyle='--', marker='x')
    axs[2].set_title('Global F1 Score')
    axs[2].set_xlabel('Round')
    axs[2].set_ylabel('F1 Score')
    axs[2].legend()
    axs[2].grid(True)
    
    plt.tight_layout()
    save_path = "comparison_metrics.png"
    plt.savefig(save_path, dpi=300)
    print(f"\n✅ Graph saved as: {save_path}")
    plt.show()

if __name__ == "__main__":
    plot_comparison()