import React, { useState, useEffect } from 'react';
import axios from 'axios';
import {
    BarChart2,
    ShieldAlert,
    ShieldCheck,
    Activity,
    Grid,
    RefreshCw,
    XCircle,
    FileText
} from 'lucide-react';

const IMG_BASE = 'http://localhost:5000/results';
const JSON_BASE = 'http://localhost:5000/results';

const ImageModal = ({ src, isOpen, onClose }) => {
    if (!isOpen) return null;
    return (
        <div
            className="fixed inset-0 z-50 flex items-center justify-center bg-black/90 backdrop-blur-sm p-4 animate-in fade-in duration-200"
            onClick={onClose}
        >
            <div className="relative max-w-[95vw] max-h-[95vh] overflow-hidden rounded-xl shadow-2xl animate-in zoom-in-95 duration-200" onClick={(e) => e.stopPropagation()}>
                <button
                    onClick={onClose}
                    className="absolute top-4 right-4 p-2 bg-black/50 hover:bg-black/70 text-white rounded-full transition-colors z-10 backdrop-blur-md"
                >
                    <XCircle className="w-6 h-6" />
                </button>
                <img
                    src={src}
                    alt="Full View"
                    className="max-w-full max-h-[90vh] w-auto h-auto object-contain bg-slate-900"
                />
            </div>
        </div>
    );
};

export default function ResultsView() {
    const [mode, setMode] = useState('no_attack'); // 'no_attack' | 'under_attack'
    const [loading, setLoading] = useState(false);
    const [results, setResults] = useState(null);
    const [error, setError] = useState(null);
    const [refreshKey, setRefreshKey] = useState(Date.now());
    const [selectedImage, setSelectedImage] = useState(null);

    // Fetch static results (created by running python script locally)
    const fetchResults = async () => {
        setLoading(true);
        setError(null);
        setResults(null);

        try {
            const filename = `comparison_results_${mode}.json`;
            const res = await axios.get(`${JSON_BASE}/${filename}?t=${Date.now()}`);
            if (res.data && res.data.success) {
                setResults(res.data);
                setRefreshKey(Date.now()); // force image reload
            } else {
                setError("Invalid results file format.");
            }
        } catch (e) {
            setResults(null);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchResults();
    }, [mode]);

    const ResultCard = ({ title, accuracy, color, icon: Icon }) => (
        <div className={`relative overflow-hidden rounded-2xl border ${color} bg-slate-800/50 p-6 transition-all hover:scale-[1.02] hover:shadow-2xl`}>
            <div className="absolute -right-4 -top-4 opacity-10">
                <Icon className="w-32 h-32" />
            </div>
            <div className="relative z-10">
                <h3 className="text-sm font-bold uppercase tracking-widest text-slate-400 mb-2">{title}</h3>
                <div className="flex items-end gap-2">
                    <span className="text-4xl font-black text-white">
                        {accuracy ? accuracy.toFixed(2) : '--'}%
                    </span>
                    <span className="text-sm font-medium text-emerald-400 mb-1">Accuracy</span>
                </div>
            </div>
        </div>
    );

    return (
        <div className="space-y-8 animate-in fade-in duration-500">
            {/* Header & Controls */}
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 pb-6 border-b border-white/5">
                <div>
                    <h2 className="text-2xl font-bold text-white flex items-center gap-3">
                        <BarChart2 className="w-8 h-8 text-blue-400" />
                        Dynamic Results Analysis
                    </h2>
                    <p className="text-slate-400 text-sm mt-1">
                        View results generated by your local analysis script.
                    </p>
                </div>

                <div className="flex bg-slate-900 rounded-xl p-1.5 border border-white/10 shrink-0">
                    <button
                        onClick={() => setMode('no_attack')}
                        className={`flex items-center gap-2 px-6 py-2.5 rounded-lg text-sm font-bold transition-all ${mode === 'no_attack'
                            ? 'bg-emerald-600 text-white shadow-lg'
                            : 'text-slate-400 hover:text-white hover:bg-white/5'
                            }`}
                    >
                        <ShieldCheck className="w-4 h-4" />
                        NO ATTACK
                    </button>
                    <button
                        onClick={() => setMode('under_attack')}
                        className={`flex items-center gap-2 px-6 py-2.5 rounded-lg text-sm font-bold transition-all ${mode === 'under_attack'
                            ? 'bg-red-600 text-white shadow-lg'
                            : 'text-slate-400 hover:text-white hover:bg-white/5'
                            }`}
                    >
                        <ShieldAlert className="w-4 h-4" />
                        UNDER ATTACK
                    </button>
                </div>
            </div>

            {/* Content Area */}
            <div className="min-h-[400px]">
                {loading ? (
                    <div className="flex flex-col items-center justify-center py-20 text-slate-500 animate-pulse">
                        <Activity className="w-8 h-8 mb-2 animate-spin" />
                        <span className="text-sm">Loading results...</span>
                    </div>
                ) : results ? (
                    <div className="space-y-8 animate-in slide-in-from-bottom-8 duration-700">
                        {/* Timestamp Info */}
                        <div className="flex justify-between items-center text-xs text-slate-500 font-mono bg-slate-900/50 p-2 rounded">
                            <span>Last Run: {results.timestamp || 'Unknown'}</span>
                            <button onClick={fetchResults} className="hover:text-white flex items-center gap-1">
                                <RefreshCw className="w-3 h-3" /> Refresh
                            </button>
                        </div>

                        {/* Accuracy Cards */}
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                            <ResultCard
                                title="Federated Averaging"
                                accuracy={results.fedavg?.accuracy}
                                color="border-blue-500/30 shadow-blue-500/10"
                                icon={Activity}
                            />
                            <ResultCard
                                title="Federated Proximal"
                                accuracy={results.fedprox?.accuracy}
                                color="border-pink-500/30 shadow-pink-500/10"
                                icon={ShieldCheck}
                            />
                        </div>

                        {/* Confusion Matrices */}
                        <div className="bg-slate-900/50 border border-white/5 rounded-2xl p-6 md:p-8">
                            <h3 className="text-xl font-bold text-white mb-6 flex items-center gap-2">
                                <Grid className="w-6 h-6 text-amber-400" />
                                Confusion Matrices
                            </h3>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                                <div className="space-y-3">
                                    <h4 className="text-sm font-bold text-blue-400 uppercase tracking-wider text-center">FedAvg</h4>
                                    <div
                                        className="bg-black/40 rounded-xl p-2 border border-white/10 overflow-hidden group cursor-pointer"
                                        onClick={() => setSelectedImage(`${IMG_BASE}/confusion_matrix_fedavg_${mode}.png?t=${refreshKey}`)}
                                    >
                                        <img
                                            src={`${IMG_BASE}/confusion_matrix_fedavg_${mode}.png?t=${refreshKey}`}
                                            alt="FedAvg CM"
                                            className="w-full h-auto rounded transition-transform duration-500 group-hover:scale-105"
                                            onError={(e) => e.target.style.opacity = '0.2'}
                                        />
                                    </div>
                                </div>
                                <div className="space-y-3">
                                    <h4 className="text-sm font-bold text-pink-400 uppercase tracking-wider text-center">FedProx</h4>
                                    <div
                                        className="bg-black/40 rounded-xl p-2 border border-white/10 overflow-hidden group cursor-pointer"
                                        onClick={() => setSelectedImage(`${IMG_BASE}/confusion_matrix_fedprox_${mode}.png?t=${refreshKey}`)}
                                    >
                                        <img
                                            src={`${IMG_BASE}/confusion_matrix_fedprox_${mode}.png?t=${refreshKey}`}
                                            alt="FedProx CM"
                                            className="w-full h-auto rounded transition-transform duration-500 group-hover:scale-105"
                                            onError={(e) => e.target.style.opacity = '0.2'}
                                        />
                                    </div>
                                </div>
                            </div>
                        </div>

                        <ImageModal
                            src={selectedImage}
                            isOpen={!!selectedImage}
                            onClose={() => setSelectedImage(null)}
                        />

                    </div>
                ) : (
                    // Empty State / Instructions
                    <div className="flex flex-col items-center justify-center py-20 text-center border-2 border-dashed border-slate-700/50 rounded-2xl bg-slate-900/20">
                        <FileText className="w-16 h-16 text-slate-600 mb-4" />
                        <h3 className="text-xl font-bold text-white mb-2">No Results Found</h3>
                        <p className="text-slate-400 max-w-md mb-6">
                            To view results, run the comparison script locally for the
                            <span className="text-white font-bold px-2 mx-1 bg-slate-800 rounded">{mode.replace('_', ' ').toUpperCase()}</span>
                            mode.
                        </p>
                        <div className="bg-black/50 p-4 rounded-lg font-mono text-xs text-blue-300 border border-slate-700 w-full max-w-2xl text-left overflow-x-auto">
                            <span className="text-slate-500"># Run this command in your terminal:</span>
                            <br />
                            {mode === 'no_attack'
                                ? 'python compare_results.py --fedavg results/fedavgeachround/round-10-weights.pkl --fedprox results/fedproxeachround/round-10-weights.pkl --mode no_attack'
                                : 'python compare_results.py --fedavg results/fedunderattack/round-10-weights.pkl --fedprox results/fedproxunderattack/round-10-weights.pkl --mode under_attack'
                            }
                        </div>
                        <button
                            onClick={fetchResults}
                            className="mt-6 flex items-center gap-2 px-6 py-2 bg-slate-700 hover:bg-slate-600 text-white rounded-lg transition-colors font-bold text-sm"
                        >
                            <RefreshCw className="w-4 h-4" /> Check Again
                        </button>
                    </div>
                )}
            </div>
        </div>
    );
}
